### ISSUE TITLE
Increase default volume size for Harbor

### ISSUE THREAD

**Issue by vaxinate** [revelrylabs/moondog-engine#65]
## Background

We have been running into issues on MDE clusters where WAL replication is getting backed up and the logs aren't getting flushed often enough and filling the disk as a result; taking down the whole DB. We believe this is mostly a result of too small default DB volumes. 1GB probably isn't really a big enough volume for Harbor, and KubeDB is pretty poor at resizing volumes after init. I think we should probably start the Harbor KubeDB off at 10GB to give plenty of room for data and logs.

**Comment by bit-herder** [comment]
this is done.
